name: Upload the Whatsapp-Dashboard to the server of the subdomain whatsapp-dashboard.friedrichvoelkers.de

on:
  push:
    branches: [ main ]

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code                     
        uses: actions/checkout@v3
      - name: 📝 Create .env.js with API key
        run: |
          echo "window.env = { API_KEY: '${{ secrets.API_KEY }}'  }" > .env.js              
      - name: 📂 SFTP uploader                       
        uses: wangyucode/sftp-upload-action@v1.4.8 # Thank you @https://github.com/wangyucode/sftp-upload-action
        with:
          host: ${{ secrets.SFTP_HOST }}                  
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          dryRun: false
          forceUpload: true                         
          localDir: './'                         
          remoteDir: '/toxmap'                       
          exclude: '.git*,.DS_Store'
      
